#include "FreeImage.h"

#ifdef __cplusplus
extern "C" {
#endif

#define FISIDECAR_LOAD_HEIF_SDR         (0x0001 << 0)
#define FISIDECAR_LOAD_HEIF_NCLX_TO_ICC (0x0001 << 1)
#define FISIDECAR_LOAD_HEIF_TRANSFORM   (0x0001 << 2)

#define FISIDECAR_LOAD_AVIF_SDR         FISIDECAR_LOAD_HEIF_SDR
#define FISIDECAR_LOAD_AVIF_NCLX_TO_ICC FISIDECAR_LOAD_HEIF_NCLX_TO_ICC
#define FISIDECAR_LOAD_AVIF_TRANSFORM   FISIDECAR_LOAD_HEIF_TRANSFORM

DLL_API FREE_IMAGE_FORMAT DLL_CALLCONV FISidecar_RegisterPluginHEIF();
DLL_API FREE_IMAGE_FORMAT DLL_CALLCONV FISidecar_RegisterPluginAVIF();

#ifdef __cplusplus
}
#endif